### PR TITLE
Add Home Destination

### PR DESCRIPTION
**Pull request by FancyGohst**

### CODE REVIEW

**Review by tianrui-qi — APPROVED** [review]
Looks fantastic. Agree to approve.

**Review by Sunnylyxxxx — APPROVED** [review]
kinda like the icon!

**Review by Sam-zzZ — APPROVED** [review]
nice code

**Review by yuwenellie — APPROVED** [review]
Looks good!

**Comment by AZLonerd** [comment]
looks very clean

**Pull request merged**
