### PR TITLE
Sprint1: Implement view and layout for Home-Accommodations

### PR DESCRIPTION
**Pull request by AZLonerd**

### CODE REVIEW

**Review by tianrui-qi — APPROVED** [review]
Thanks Yuang. Great Job.

**Review by yuwenellie — APPROVED** [review]
Good work, thanks!

**Review by Sunnylyxxxx — APPROVED** [review]
:)good!

**Review by FancyGohst — APPROVED** [review]
Gj on implementing home accommodations

**Review by Sam-zzZ — APPROVED** [review]
good job

**Pull request merged**
